services:
  - type: worker
    name: telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3.11 python3.11-venv python3.11-distutils
      python3.11 -m venv venv
      . venv/bin/activate
      pip install -U pip setuptools
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate && python bot.py
